const json_celestialBody = [{
        "type": "Planeta",
        "name": "Mercurio",
        "mass": "3,285 × 10^23",
        "medium_temp": "440 K (166 °C)",
        "duration_day": "58d 15h 30m",
        "distance_averageSun": "57.91 millones km",
        "one_yearDuration": "88 años",
        "satellites": [],
    }, {
        "type": "Planeta",
        "name": "Venus",
        "mass": "4,867 × 10^24",
        "medium_temp": "463,85 ºC",
        "duration_day": "116d 18h 0m",
        "distance_averageSun": "108.2 millones km",
        "one_yearDuration": "225 años",
        "satellites": [],
    }, {
        "type": "Planeta",
        "name": "Marte",
        "mass": "6,39 × 10^23",
        "medium_temp": "218 K (-55 °C).",
        "duration_day": "1d 0h 37m",
        "distance_averageSun": "227,9 millones km",
        "one_yearDuration": "687 días",
        "satellites": [{
            "type": "Satélite",
            "name": "Fobos",
            "belong_planet": "Marte",
            "distance_celestialBody": "9377 km",
            "principal_characteristics": "Es la más grande de las dos lunas de Marte y la más cercana al planeta,",
        }, {
            "type": "Satélite",
            "name": "Deimos",
            "belong_planet": "Marte",
            "distance_celestialBody": "23460 km",
            "principal_characteristics": "Deimos (del griego Δείμος, «terror») es el más pequeño y externo de los dos satélites de Marte y de los satélites más pequeños que han recibido nombre, llamado así por Deimos, un personaje de la mitología griega",
        }]
    }, {
        "type": "Planeta",
        "name": "Júpiter",
        "mass": "1,898 × 10^27",
        "medium_temp": "52 K-121,15 °C",
        "duration_day": "0d 9h 56m",
        "distance_averageSun": "588000000 km",
        "one_yearDuration": "12 años",
        "satellites": [{
            "type": "Satélite",
            "name": "Europa",
            "belong_planet": "Júpiter",
            "distance_celestialBody": "670.900 km",
            "principal_characteristics": "Es el sexto satélite natural de Júpiter en orden creciente de distancia y el más pequeño de los cuatro satélites galileanos.",
        }, {
            "type": "Satélite",
            "name": "Ganimedes",
            "belong_planet": "Júpiter",
            "distance_celestialBody": "1.070000 km",
            "principal_characteristics": "Es el satélite natural más grande de Júpiter y del sistema solar,​ además de ser el único que tiene campo magnético.",
        }, {
            "type": "Satélite",
            "name": "Ío",
            "belong_planet": "Júpiter",
            "distance_celestialBody": "421800 km",
            "principal_characteristics": "Es el satélite galileano más cercano a Júpiter. Es el tercer satélite por su tamaño, tiene la más alta densidad entre todos los satélites y, en proporción, la menor cantidad de agua entre todos los objetos conocidos del sistema solar",
        }],
    }, {
        "type": "Planeta",
        "name": "Saturno",
        "mass": "5,683 × 10^26",
        "medium_temp": "143K -130,15°C",
        "duration_day": "0d 10h 42m",
        "distance_averageSun": "1418 millones km",
        "one_yearDuration": "29 años",
        "satellites": [{
            "type": "Satélite",
            "name": "Titán",
            "belong_planet": "Saturno",
            "distance_celestialBody": "1.22 millones de kilómetros",
            "principal_characteristics": "Único satélite conocido que posee una atmósfera importante,1​ y el único objeto, aparte de la Tierra, en el que se ha encontrado evidencia clara de cuerpos líquidos estables en la superficie.",
        }, {
            "type": "Satélite",
            "name": "Encélado ",
            "belong_planet": "Saturno",
            "distance_celestialBody": "238.100 millones de km",
            "principal_characteristics": "Está cubierto por una capa de hielo reciente y limpio que refleja casi toda la luz solar que incide sobre él, por lo que la temperatura superficial solo alcanza los –198 °C a mediodía. A pesar de su pequeño tamaño, tiene una amplia variedad de rasgos superficiales que van desde regiones antiguas y craterizadas a terrenos jóvenes y deformados tectónicamente que se formaron hace apenas cien millones de años",
        }, {
            "type": "Satélite",
            "name": "Mimas",
            "belong_planet": "Saturno",
            "distance_celestialBody": "",
            "principal_characteristics": "185.600 millones de km",
        }, {
            "type": "Satélite",
            "name": "Dione",
            "belong_planet": "Saturno",
            "distance_celestialBody": "377.400 millones de km",
            "principal_characteristics": "Dione está compuesto principalmente de agua congelada. Sin embargo, dado que Dione es la luna más densa de Saturno (aparte de Titán, cuya densidad es mayor por compresión gravitacional), seguramente debe tener materiales más densos en su interior, como por ejemplo rocas de silicio",
        }],
    }, {
        "type": "Planeta",
        "name": "Urano",
        "mass": "8,681 × 10^25",
        "medium_temp": "68 Kelvin (−205,2 °C) ",
        "duration_day": "0d 17h 14m",
        "distance_averageSun": "2 600 000 000 kilómetros",
        "one_yearDuration": "84 años",
        "satellites": [{
            "type": "Satélite",
            "name": "Umbriel",
            "belong_planet": "Urano",
            "distance_celestialBody": "266.000 km",
            "principal_characteristics": "A diferencia de los otros satélites uranianos, los cráteres de impacto de Umbriel son oscuros, haciendo que la superficie solo refleje un 16 % de la luz incidente, siendo por tanto el satélite de Urano con menor albedo",
        }, {
            "type": "Satélite",
            "name": "Oberón",
            "belong_planet": "Urano",
            "distance_celestialBody": " 660.000 km",
            "principal_characteristics": "Está compuesto de partes aproximadamente iguales de hielo y roca que están probablemente diferenciados en un núcleo rocoso y un manto de hielo",
        }, {
            "type": "Satélite",
            "name": "Titania",
            "belong_planet": "Urano",
            "distance_celestialBody": "436.000 km",
            "principal_characteristics": "Titania tiene un brillo intermedio entre los más oscuros Oberón y Umbriel y los más brillantes Ariel y Miranda.",
        }],
    }, {
        "type": "Planeta",
        "name": "Neptuno",
        "mass": "1,024 × 10^26",
        "medium_temp": " -218 °C (55 K)",
        "duration_day": "0d 16h 6m",
        "distance_averageSun": "4 300 000 000 kilómetros",
        "one_yearDuration": "165 años",
        "satellites": [{
            "type": "Satélite",
            "name": "Tritón",
            "belong_planet": "Neptuno",
            "distance_celestialBody": "354.300 km",
            "principal_characteristics": "Es el único satélite de Neptuno que tiene forma esférica.",
        }, {
            "type": "Satélite",
            "name": "Talasa",
            "belong_planet": "Neptuno",
            "distance_celestialBody": "50.074 km",
            "principal_characteristics": "La órbita que traza Talasa, sigue la misma dirección que el movimiento de rotación del planeta. Al igual que su satélite homólogo Náyade, está recibiendo una aceleración negativa, lo que puede llegar a producir un impacto contra la atmósfera de Neptuno, o un impacto contra sus anillos.",
        }, {
            "type": "Satélite",
            "name": "Náyade",
            "belong_planet": "Neptuno",
            "distance_celestialBody": "48.227 km",
            "principal_characteristics": "Naiad o Náyade es una pequeña e irregular luna del planeta Neptuno también conocida como Neptuno III y anteriormente designada como S/1989 N 6.",
        }, {
            "type": "Satélite",
            "name": "Nereida",
            "belong_planet": "Neptuno",
            "distance_celestialBody": "5.513.400 km",
            "principal_characteristics": "Su órbita es muy elíptica, por lo que podría tratarse de un objeto capturado. Apenas se conocen detalles de su superficie. ",
        }],
    }, {
        "type": "Estrella",
        "name": "Sol",
        "mass": " 1,9891 × 1030",
        "medium_temp": "5.778 K",
        "duration_day": "24 horas",
        "age": "4,603 miles de millones años",
        "composition": "hidrógeno y helio",
        "luminous_intesi": "93 lumenes",
        "size": "696.340 km",
    }, {
        "type": "Estrella",
        "name": "Sirio",
        "mass": "1,9891·1030 kg",
        "medium_temp": "9.940 K",
        "duration_day": "",
        "age": " Entre 2·108 y 3·108",
        "composition": "carbono y oxígeno",
        "luminous_intesi": "-1.5 m",
        "size": "1,19 millones km",
    },
    {
        "type": "Planeta",
        "name": "Tierra",
        "mass": "5,972 × 10^24 kg",
        "medium_temp": "287,2 K,​ 14,05 °",
        "duration_day": "24h",
        "distance_averageSun": "149,6 millones km",
        "one_yearDuration": "365 d",
        "satellites": [{
            "type": "Satélite",
            "name": "Luna",
            "belong_planet": "Tierra",
            "distance_celestialBody": "384.400 km",
            "principal_characteristics": "La luna es el único satélite de la tierra, pero ha sido clave para que la misma sea como es ahora y, sobre todo, sin ella, hubiera sido imposible que se dieran las condiciones para la vida en nuestro planeta. La luna es esencial para que las mareas sean posibles.",
        }],
    }
]