const json_programs = [{
        "type": "Programa Espacial",
        "name": "Gemini",
        "date_start": "1964-04-8",
        "date_end": "1999-06-7",
        "descrip_scope": "Probar los nuevos motores de plasma",
        "missions": [{
            "type": "Misión",
            "name": "Redstone 1",
            "crew": "Pedro,Bruce,Angelo",
            "relase_date": "1964-06-10",
            "length_time": "4 horas",
            "important_data": "Primer intento de vuelo",
            "result": "Fracaso",
            "name_ship": "Bell 127",
            "belong_program": "Gemini",
            "destination_place": [],
        }, {
            "type": "Misión",
            "name": "Redstone 2",
            "crew": "Pedro,Bruce,Angelo",
            "relase_date": "1964-06-20",
            "length_time": "4 horas",
            "important_data": "Segundo intento de vuelo",
            "result": "Exito",
            "name_ship": "Bell 127",
            "belong_program": "Gemini",
            "destination_place": [],
        }]
    }, {
        "type": "Programa Espacial",
        "name": "Capricornio",
        "date_start": "1996-01-12",
        "date_end": "2008-04-12",
        "descrip_scope": "Primer vuelo a marte con un ser vivo",
        "missions": [{
            "type": "Misión",
            "name": "Dante 44",
            "crew": "Dante",
            "relase_date": "2005-06-03",
            "length_time": "3 años,22 horas.60 segundos",
            "important_data": "El primer vuelo a marte de prueba",
            "result": "Regular",
            "name_ship": "Titan",
            "belong_program": "Capricornio",
            "destination_place": [{
                "type": "Planeta",
                "name": "Marte",
                "mass": "6,39 × 10^23",
                "medium_temp": "218 K (-55 °C).",
                "duration_day": "1d 0h 37m",
                "distance_averageSun": "227,9 millones km",
                "one_yearDuration": "687 días",
                "satellites": [{
                    "type": "Satélite",
                    "name": "Fobos",
                    "belong_planet": "Marte",
                    "distance_celestialBody": "9377 km",
                    "principal_characteristics": "Es la más grande de las dos lunas de Marte y la más cercana al planeta,",
                }, {
                    "type": "Satélite",
                    "name": "Deimos",
                    "belong_planet": "Marte",
                    "distance_celestialBody": "23460 km",
                    "principal_characteristics": "Deimos (del griego Δείμος, «terror») es el más pequeño y externo de los dos satélites de Marte y de los satélites más pequeños que han recibido nombre, llamado así por Deimos, un personaje de la mitología griega"
                }]
            }]
        }]
    },
    {
        "type": "Programa Espacial",
        "name": "Gemini 2",
        "date_start": "1965-01-19",
        "date_end": "2000-06-7",
        "descrip_scope": "Vuelo suborvital para probar el escudo termico de rentrada",
        "missions": [{
            "type": "Misión",
            "name": "Redstone 4",
            "crew": "Pedro,Bruce,Angelo",
            "relase_date": "1964-06-10",
            "length_time": "4 dias 1 hora 56 minutos 14 segundos",
            "important_data": "probar el escudo termico de rentrada",
            "result": "Exito",
            "name_ship": "Bell 127",
            "belong_program": "Gemini 2",
            "destination_place": [],
        }]
    },
    {
        "type": "Programa Espacial",
        "name": "Canadarm 2",
        "date_start": "1969-01-19",
        "date_end": "2000-06-7",
        "descrip_scope": "es un sistema robotizado y de equipamiento asociado a la Estación Espacial Internacional. Tiene un importante papel en el ensamblaje y mantenimiento de la estación",
        "missions": [],
    }, {
        "type": "Programa Espacial",
        "name": "Mercury",
        "date_start": "1960-09-21",
        "date_end": "2000-06-7",
        "descrip_scope": "Intentar llevar al hombre al espacio",
        "missions": [{
            "type": "Misión",
            "name": "Redstone 5",
            "crew": "Virgil I. Grissom",
            "relase_date": "1960-12-19",
            "length_time": "13 días, 18horas, 3 minutos,1 segundo",
            "important_data": "Vuelo suborbital",
            "result": "Exito",
            "name_ship": "Liberty Bell",
            "belong_program": "Mercury",
            "destination_place": [],
        }]
    },
    {
        "type": "Programa Espacial",
        "name": "Programa Apolo",
        "date_start": "1961-08-27",
        "date_end": "1972-12-19",
        "descrip_scope": "Intentar el sobrevuelo tripulado de nuestro satélite para localizar una zona apropiada con vistas a un eventual alunizaje de astronautas, que cumpliría así el viejo sueño del viaje a la Luna por parte del ser humano",
        "missions": [{
            "type": "Misión",
            "name": "Apolo 1",
            "crew": "Grissom, White y Chaffee",
            "relase_date": "1967-02-21",
            "length_time": "14 días",
            "important_data": "Prueba de verificación de la nave espacial con tripulación.",
            "result": "fracaso",
            "name_ship": "Apolo",
            "belong_program": "Programa Apolo",
            "destination_place": [],
        }, {
            "type": "Misión",
            "name": "Apolo 11",
            "crew": "Armstrong, Collins y Aldrin",
            "relase_date": "1969-06-16",
            "length_time": "14 días",
            "important_data": "Lograr que un ser humano caminara en la superficie de la Luna",
            "result": "Exitoso",
            "name_ship": "Columbia",
            "belong_program": "Programa Apolo",
            "destination_place": [{
                "type": "Satélite",
                "name": "Luna",
                "belong_planet": "Tierra",
                "distance_celestialBody": "384.400 km",
                "principal_characteristics": "La luna es el único satélite de la tierra, pero ha sido clave para que la misma sea como es ahora y, sobre todo, sin ella, hubiera sido imposible que se dieran las condiciones para la vida en nuestro planeta. La luna es esencial para que las mareas sean posibles.",
            }],
        }]
    }

]